### PR TITLE
Update smallrye-metrics to clean up application registry on undeploy

### PR DESCRIPTION
**Pull request by jasondlee**
Modify MetricsMetadata.registerMetrics to return list of MetricIDs registered
Modify MetricCdiInjectionExtension to store MetricID list in ivar
Add observer method for BeforeShutdown that filters application registry, removing any metrics in MetricID list

### CODE REVIEW

**Comment by jmartisk** [comment]
Looks good, but this only cleans up annotated metrics. Should we also handle metrics created by applications calling the `MetricRegistry`? That will be a bit more difficult I think. I think the `MetricsRegistryImpl` (or rather something in WildFly that decorates it, we probably don't want this in SmallRye directly because it's too WF-specific) will need to determine which deployment is the one registering a metric, perhaps by looking at the current TCCL (or is there a better way how to identify a deployment that calls some code?), and maintain a list of such metrics pertaining to the deployment..

**Comment by jmesnil** [comment]
This looks good to me.

@jmartisk is right that metrics created programmatically by applications will not be taken into account. However, that's up to the developers of these applications to make sure that they clean up resources if their applications is undeployed.

But that's fine to me: at least, using CDI means that "managed" metrics are properly cleaned up and programmatic "unmanaged" metrics are the responsibility of the developer that creates them.

**Comment by jmartisk** [comment]
Ok, it didn't occur to me that we could actually leave the cleanup up to the developer, but it makes sense, and simplifies things for us quite a lot. It's probably something that deserves a mention in WF/EAP documentation (unless it's there already)

**Review by jmartisk — APPROVED** [review]

**Comment by jasondlee** [comment]
Thanks to both of you!

**Pull request merged**
