### PR TITLE
Revert "Move to Jakarta dependencies"

### PR DESCRIPTION
**Pull request by jmartisk**
This reverts commit 6c64ac3e7c4066db21c6840335f0a1fa2f2101b0.

### CODE REVIEW

**Comment by kenfinnigan** [comment]
Do we need to revert?

I was thinking we could just exclude javax artifacts from API dependency on a temporary basis

**Comment by jmartisk** [comment]
Hmmmm. So you mean we would exclude javax artifacts that are imported by the MP API and compile with jakarta, and then run with javax artifacts again in the runtime? That might technically work, but it sounds like a weird hybrid to me?!

**Comment by jmartisk** [comment]
smallrye-parent 15 now defines jakarta dependencies only, so if we want to compile against javax dependencies, we will probably need a new release there

**Comment by kenfinnigan** [comment]
Runtime wouldn't be using javax.

WildFly, Quarkus, and likely Thorntail, or soon, already use Jakarta EE 8 artifacts

**Comment by jmartisk** [comment]
Hmm. Ok, that sounds reasonable then. I'll close this and create a new PR (maybe it will not be needed  at all, because the javax dependencies in API dependency are `provided`, will double check)

**Comment by Ladicek** [comment]
Thorntail 2.6, with the move to WildFly 18, also moved to Jakarta EE 8 artifacts. I actually also have an open PR to update SmallRye Fault Tolerance to Jakarta dependencies, but I'm not totally sure whether to merge it or not.

**Comment by kenfinnigan** [comment]
@jmartisk right, it's only for non provided dependencies we'd need an exclusion.

@Ladicek, I'd move to Jakarta. Would be good to have all SmallRye projects on Jakarta for next release

**Pull request closed without merging**
