### PR TITLE
Micrometer custom scopes + other fixes

### LINKED ISSUE #502: [metrics 5.0] allow application metrics to have a custom scope
application metrics may have a custom scope defined in the scope tag of the newly created metric.

custom scope tag value is not allowed to be "base", "vendor" or "application" (throw an IllegalArgumentException if this is attempted)

metrics which have a custom scope defined must appear to users of the MetricRegistry to be just like any other metric.  For example, querying for metricRegistry.getCounters() from the application MetricRegistry must return all counters from that registry, regardless of scope.

it must be easy to get a Prometheus-formatted output for a subset of metrics in the application MetricRegistry filtered by scope (so that endpoints can filter metrics by scope - eg. /metrics?scope=dragons)

It must also be easy to get a Prometheus-formatted output for a subset of metrics in any MetricRegistry filtered by scope and metric name (so that endpoints can filter metrics by scope and name - eg. /metrics?scope=dragons&name=dragon_visits )

It must also be possible to inject a MetricRegistry with a custom scope using the `@RegistryType` annotation

### LINKED ISSUE #516: [Metrics 5.0] Use query parameters to specify scope
Add the ability to use query parameters to obtain the scope and metric name.

From
`/metrics/<scope>/<metric_name>`

To:
`/metrics?scope=<scope>&name=<name>`

Also provide the ability to query a metric name by itself and return all hits across all scopes:
e.g.

`/metrics?name=<name>`

### LINKED ISSUE #519: [Metrics 5.0] Use of "Prometheus Exporter"
As per the MP Metrics Specification (for the upcoming MP Metrics 5.0). The expected required format should be in Prometheus format with OpenMetrics format being optional.

With Micrometer (v1.8.5), the Prometheus java client, which is used to scrape and format data from the Prometheus Meter Registry does not _fully_ support the Open Metrics format.

OpenMetrics exporter can be re-introduced in a future time.

This also applies to the more up to date micrometer v1.9.5

### LINKED ISSUE #520: [Metrics 5.0] Metrics registered must already be converted to the Prometheus suggested base units
By depending on the Prometheus client to format metrics we do not have control of the formatting and output.

The `base` metrics must be pre-converted to base units.

### PR DESCRIPTION
**Pull request by Channyboy**
Related to : https://github.com/eclipse/microprofile-metrics/pull/667 

Fixes #516 
Fixes #502 
Fixes #519
Fixes #520

### CODE REVIEW

**Comment by jgallimore** [comment]
I note in the PR for MP Metrics 5.0 API changes, that the URL to get the metrics for a specific scope is: `/metrics?scope=<scope>` - do we need a corresponding change in src/main/java/io/smallrye/metrics/MetricsRequestHandler.java, or a change in the API? Currently it looks like the URL Smallrye is using is still `/metrics/<scope>`.

https://github.com/eclipse/microprofile-metrics/pull/668/files#diff-fafadf2a285d0a6a99f0933c4adf60301ea74bb399618d22613b27ec2818d6dcL59

**Comment by Channyboy** [comment]
Including 3 fixes as part of this PR to stream line.
Descriptions of fixes are in the commits.

**Comment by Channyboy** [comment]
Included one more fix regarding unit suffixes appended to the calculated metric names.
Also, forgot to mention PR updated to be able to query scope and names with params

**Comment by Channyboy** [comment]
@jgallimore 
Updated to now be able to query across scopes.

from before:
- updated to use base units
- use prometheus exporter over open metrics exporter

**Pull request merged**
