### PR TITLE
Remove camelCase to snake_case conversion. Fixes #93

### LINKED ISSUE #93: Remove camelCase to snake_case conversion
This is a spec change through https://github.com/eclipse/microprofile-metrics/pull/363

### PR DESCRIPTION
**Pull request by jmartisk**
https://github.com/smallrye/smallrye-metrics/issues/93

### CODE REVIEW

**Comment by jmartisk** [comment]
Failures are expected because MP Metrics 2.0-SNAPSHOT-2.1 doesn't contain TCK updates... It passes 100% for me against the current snapshot

**Comment by manovotn** [comment]
> Failures are expected because MP Metrics 2.0-SNAPSHOT-2.1 doesn't contain TCK updates... It passes 100% for me against the current snapshot

@jmartisk is the SNAPSHOT with the tck changes going to be available any time soon or do you aim to merge this prior to that?

**Comment by jmartisk** [comment]
@pilhuhn can release a new snapshot of the spec. WDYT, should we? The bad thing is that there's a lot of stuff going on there, and releasing a new snapshot after every change that affects TCKs... would mean potetntially a big number of snapshots.

There is also the option to add a new job in Semaphore that clones the microprofile-metrics repo, builds a fresh snapshot from master and runs the TCKs against that snapshot. I have exactly this in my own Semaphore project, but don't have the permission to change the official one.

**Comment by manovotn** [comment]
Oh, I thought the have some nightly builds for snapshots.
In that case, I'd be neat to have semaphore build the snapshot for us before running the build. I should have access but don't really know how to set it up.

**Comment by manovotn** [comment]
Alright, I have changed Semaphore and added secondary build that will clone the spec, build it and subsequently build SmallRye impl with that SNAPSHOT.
This sadly means that there will still be failures on CI (just like now, against last released snapshot it would fail) but at least upon inspecting the job you can see secondary one that should pass.

**Pull request merged**
