### PR TITLE
[ISSUE-55] add priviledgd createion of Metadata

### PR DESCRIPTION
**Pull request by baranowb**
https://github.com/smallrye/smallrye-metrics/issues/55

### CODE REVIEW

**Comment by kenfinnigan** [comment]
As the TCK fails, we wouldn't be able to consider merging this change as is

**Comment by baranowb** [comment]
Weird, it did pass locally. Let me check.

**Comment by kenfinnigan** [comment]
I think that makes sense.

**Comment by jmesnil** [comment]
FIY, I saw this issue after I filed 
https://github.com/eclipse/microprofile-metrics/issues/315 (with PR for the 1.x and master branches)

**Comment by jmartisk** [comment]
Closing, see https://github.com/smallrye/smallrye-metrics/issues/55#issuecomment-504892104

**Pull request closed without merging**
